<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- Consider the following (rather contrived) object:

var box = {
  locked: true,
  unlock: function() { this.locked = false; },
  lock: function() { this.locked = true;  },
  _content: [],
  get content() {
    if (this.locked) throw new Error("Locked!");
    return this._content;
  }
};
It is a box with a lock. Inside is an array, but you can get at it only when the box is unlocked. Directly accessing the _content property is not allowed.

Write a function called withBoxUnlocked that takes a function value as argument, unlocks the box, runs the function, and then ensures that the box is locked again before returning, regardless of whether the argument function returned normally or threw an exception.

function withBoxUnlocked(body) {
  // Your code here.
}

withBoxUnlocked(function() {
  box.content.push("gold piece");
});

try {
  withBoxUnlocked(function() {
    throw new Error("Pirates on the horizon! Abort!");
  });
} catch (e) {
  console.log("Error raised:", e);
}
console.log(box.locked);
// â†’ true
For extra points, make sure that if you call withBoxUnlocked when the box is already unlocked, the box stays unlocked. -->

    <script>
        var box = {
            locked: true,
            unlock: function () { this.locked = false; },
            lock: function () { this.locked = true; },
            _content: [],
            get content() {
                if (this.locked) {
                    throw new Error('Locked!');
                }
                return this._content;
            }
        };

        function withBoxUnlocked(body) {
            // need to lock the box no matter
            // if the body function succeeds or fails
            box.unlock();
            try {
                return body();
                // This is where the finally block comes in,
                // which will be executed after the attempt,
                // regardless of whether it was successful.
                // Since you need to block it anyway, we use
                // a finally block for this
            } finally {
                box.lock();
            }
        }

        withBoxUnlocked(function () {
            box.content.push('gold piece');
        });
        try {
            withBoxUnlocked(function () {
                throw new Error('Pirates on the horizon! Abort!');
            });
        } catch (e) {
            console.log('Error raised:', e);
        }

    </script>
</body>

</html>